# Generated by Django 4.2.1 on 2023-07-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
