# Generated by Django 4.2.2 on 2023-07-04 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
