# Generated by Django 4.2.1 on 2023-06-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.AddField(
            model_name='auctions',
            name='bid',
            field=models.ForeignKey(default=0.0, on_delete=set, related_name='Current_Bid', to='auctions.bids'),
            preserve_default=False,
        ),
    ]
