# Generated by Django 4.2.1 on 2023-06-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bids_auctions_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='bid',
        ),
        migrations.AddField(
            model_name='auctions',
            name='image',
            field=models.ImageField(default='None', upload_to='auction_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctions',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bids',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
    ]
