# Generated by Django 4.2.1 on 2023-06-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auctions_bid_auctions_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.ImageField(upload_to='media/auction_images'),
        ),
    ]
