# Generated by Django 4.2.2 on 2023-07-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctions_end_time_alter_auctions_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
