# Generated by Django 4.2.1 on 2023-06-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.ImageField(upload_to='auction_images'),
        ),
    ]
