# Generated by Django 4.2.1 on 2023-06-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
            preserve_default=False,
        ),
    ]
