# Generated by Django 4.2.2 on 2023-06-26 13:12

import auctions.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctions_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='end_time',
            field=models.DateTimeField(default=auctions.models.Auctions.now_plus_7),
        ),
        migrations.AddField(
            model_name='auctions',
            name='start_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
