# Generated by Django 4.2.1 on 2023-07-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctions_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
