# Generated by Django 4.2.2 on 2023-06-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctions_end_time_auctions_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
