# Generated by Django 4.2.1 on 2023-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctions_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='auctions',
            name='category',
        ),
        migrations.AddField(
            model_name='auctions',
            name='categories',
            field=models.ManyToManyField(blank=True, to='auctions.category'),
        ),
    ]
