# Generated by Django 4.2.1 on 2023-07-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_category_remove_auctions_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='categories',
        ),
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
            preserve_default=False,
        ),
    ]
